Sys.setenv(LANG = "EN")
suppressPackageStartupMessages({
  library(stringr)
  library(viridis)
  library(ggplot2)
  library(ggnewscale)
  library(reshape2)
  library(data.table)
  library(purrr)
  library(Hmisc)
  library(ggpubr)
  library(shinyjs)
  library(shiny)
  library(shinyWidgets)
  library(shinyFiles)
  library(magick)
  library(knitr)
  library(patchwork)
  library(ComplexHeatmap)
  library(circlize)
  library(ggfortify)
  library(gridBase)
  library(ggrepel)
  library(limma)
  library(RColorBrewer)
  library(plotly)
  library(car)
  library(GEOquery)
  library(DT)
  library(forcats)
  library(scales)
  library(xlsx)
  library(wesanderson)
  library(proBatch)
  library(clusterProfiler)
  library(EnrichmentBrowser)
  library(enrichplot)
  library(Rtsne)
  library(foreach)
  library(rmarkdown)
  library(Seurat)
  library(SeuratDisk)
  library(scCustomize)
  library(tidyverse)
  library(plyr)
  library(shinyjs)
  library(httr)
})
options(dplyr.summarise.inform = FALSE)
options(clusterProfiler.download.method = "auto")

## Set multicore processor for foreach loops ------------------------------------------------------------------------
# n.cores <- parallel::detectCores() - 1
# doParallel::registerDoParallel(cl = parallel::makeCluster(n.cores, type = "PSOCK"))
# rm(n.cores)